inherit_mode:
  merge:
    - Include

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['\A#']
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/GuardClause:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Rails/EnvironmentVariableAccess:
  AllowReads: true
Rails/UniqueValidationWithoutIndex:
  Enabled: false
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/HookArgument:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ExpectChange:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: false
RSpec/EmptyLineAfterFinalLet:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
